# Generated by Django 6.0.7 on 2026-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripsession',
            name='games_shown',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
