# Generated by Django 6.0.7 on 2026-07-07 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_games', '0001_initial'),
        ('games', '0005_alter_analyticsevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryEnding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
                ('text_fr', models.TextField()),
                ('text_es', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_endings', to='games.genre')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
    ]
