# Generated by Django 6.0.7 on 2026-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_games', '0002_storyending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doodledrawing',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
