# Generated by Django 6.0.7 on 2026-07-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_games', '0003_alter_doodledrawing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceprompt',
            name='age_group',
            field=models.CharField(choices=[('toddler', 'Toddler'), ('prek', 'Pre-K'), ('elementary', 'Elementary'), ('all', 'All Ages')], db_index=True, default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='faceprompt',
            name='category',
            field=models.CharField(choices=[('silly', 'Silly'), ('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('scared', 'Scared'), ('sleepy', 'Sleepy'), ('brave', 'Brave'), ('grumpy', 'Grumpy'), ('funny', 'Funny')], db_index=True, default='silly', max_length=20),
        ),
    ]
