# Generated by Django 6.0.7 on 2026-07-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_games', '0006_alter_faceprompt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='doodledrawing',
            name='anonymous_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
