# Generated by Django 6.0.7 on 2026-07-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0005_alter_analyticsevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipSyncSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='lipsync/')),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lip_sync_sounds', to='games.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoundFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sfx/')),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_fx', to='games.genre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MicroChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
                ('text_fr', models.TextField()),
                ('text_es', models.TextField()),
                ('age_group', models.CharField(choices=[('toddler', 'Toddler'), ('prek', 'Pre-K'), ('elementary', 'Elementary')], db_index=True, max_length=20)),
                ('energy_level', models.CharField(choices=[('calm', 'Calm'), ('wild', 'Wild')], db_index=True, max_length=20)),
                ('duration_seconds', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_challenges', to='games.genre')),
            ],
            options={
                'ordering': ['?'],
                'indexes': [models.Index(fields=['age_group', 'energy_level'], name='sound_games_age_gro_b4ad93_idx')],
            },
        ),
        migrations.CreateModel(
            name='WYRQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('silly', 'Silly'), ('deep', 'Deep'), ('food', 'Food')], db_index=True, max_length=20)),
                ('option_a_en', models.TextField()),
                ('option_a_fr', models.TextField()),
                ('option_a_es', models.TextField()),
                ('option_b_en', models.TextField()),
                ('option_b_fr', models.TextField()),
                ('option_b_es', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyr_questions', to='games.genre')),
            ],
            options={
                'ordering': ['?'],
                'indexes': [models.Index(fields=['category'], name='sound_games_categor_a0ee04_idx')],
            },
        ),
    ]
