# Generated by Django 6.0.7 on 2026-07-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_delete_soundeffect'),
        ('sound_games', '0002_alter_wyrquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyrquestion',
            name='age_group',
            field=models.CharField(choices=[('all', 'All Ages'), ('3-6', '3-6'), ('7-10', '7-10'), ('11+', '11+')], db_index=True, default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='wyrquestion',
            name='category',
            field=models.CharField(choices=[('silly', 'Silly'), ('deep', 'Deep'), ('food', 'Food'), ('animals', 'Animals'), ('superpower', 'Superpower'), ('gross', 'Gross'), ('adventure', 'Adventure'), ('school', 'School')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='wyrquestion',
            index=models.Index(fields=['age_group'], name='sound_games_age_gro_fb5c46_idx'),
        ),
    ]
