# Generated by Django 6.0.7 on 2026-07-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_soundeffect_storyseed_userprofile_analyticsevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='game_module',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. giggle_generators, choice_chaos — blank uses generic detail view', max_length=50),
        ),
    ]
