# Generated by Django 6.0.7 on 2026-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_rename_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('prompt_view', 'Prompt View'), ('prompt_reroll', 'Prompt Reroll'), ('genre_enter', 'Genre Enter'), ('genre_abandon', 'Genre Abandon'), ('favorite_add', 'Favorite Added'), ('favorite_remove', 'Favorite Removed'), ('language_switch', 'Language Switch'), ('wyr_vote', 'WYR Vote'), ('wild_reaction', 'Wild Role Reaction'), ('giggle_reroll', 'Giggle Reroll'), ('mimic_play', 'Mimic Sound Played'), ('lipsync_play', 'Lip Sync Sound Played')], db_index=True, max_length=50),
        ),
    ]
