# Generated by Django 6.0.7 on 2026-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_analyticsevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name_es',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='genre',
            name='name_fr',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='genre',
            name='tagline_es',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='genre',
            name='tagline_fr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
