# Generated by Django 6.0.7 on 2026-07-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_genre_name_es_genre_name_fr_genre_tagline_es_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='genre',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to restrict to testers and show "Coming soon"'),
        ),
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Default sort order (lower = first)'),
        ),
    ]
