# Generated by Django 6.0.7 on 2026-07-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_genre_options_genre_is_active_genre_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('dealt_with', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('suggestion_text', models.TextField(help_text='Original suggestion from user')),
                ('text_en', models.TextField(blank=True, help_text='English version (fill when accepting)')),
                ('text_fr', models.TextField(blank=True, help_text='French version (fill when accepting)')),
                ('text_es', models.TextField(blank=True, help_text='Spanish version (fill when accepting)')),
                ('target_model', models.CharField(choices=[('prompt', 'Generic Prompt'), ('story_seed', 'Tale Twisters — Story Starter'), ('story_twist', 'Tale Twisters — Twist'), ('story_ending', 'Tale Twisters — Ending'), ('face_prompt', 'Funny Face Factory — Prompt'), ('micro_challenge', 'Giggle Generators — Challenge')], default='prompt', max_length=30)),
                ('category', models.CharField(blank=True, help_text='For Prompt / Story Seed', max_length=50)),
                ('age_group', models.CharField(blank=True, choices=[('', '---------'), ('toddler', 'Toddler'), ('prek', 'Pre-K'), ('elementary', 'Elementary')], help_text='For MicroChallenge', max_length=20)),
                ('energy_level', models.CharField(blank=True, choices=[('', '---------'), ('calm', 'Calm'), ('wild', 'Wild')], help_text='For MicroChallenge', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='For MicroChallenge (default 20)', null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('prompt_created', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
