# Generated by Django 6.0.7 on 2026-07-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_gamesuggestion_age_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoundEffect',
        ),
    ]
