# Generated by Django 6.0.7 on 2026-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_delete_soundeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='genre',
            name='description_fr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
